version: 2
jobs:
  build:
    working_directory: ~/Proconf
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: Proconf
          RAILS_ENV: development
      - image: postgres:11.4
        environment:
          POSTGRES_USER: Proconf
          POSTGRES_DB: Proconf_development
          POSTGRES_PASSWORD: ""
    steps:
        - checkout

      # Setup the environment
      - run: bundle install

      # Setup the database
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate
      - run: bundle exec rake db:seed

      # Run the tests
      - run: bundle exec rubocop